### PR TITLE
added different special functions and fixed minor stuff

### PR DESCRIPTION
**Pull request by fishfollower**
e.g. 
* mini function add example 
* Vectorize macro 
* pbeta
* qbeta (fixed bug in function and 3. order der)
* bessel K,J,I, and Y functions 
* kludge to report 2. der

### CODE REVIEW

**Comment by johnoel** [comment]
Going to try again.

**Comment by johnoel** [comment]
Reopen

**Comment by johnoel** [comment]
Ignore codecov warnings...

**Comment by fishfollower** [comment]
Thanks a lot for your help!
Den 08/07/2016 21.44 skrev "johnoel" <notifications@github.com>:

**Comment by johnoel** [comment]
When you get a chance, please add test code for the new functions.

**Pull request merged**
