### PR TITLE
Update error messages in read_mle_hmc function to be more informative

### PR DESCRIPTION
**Pull request by Cole-Monnahan-NOAA**
Update error messages in a single HMC function. No change to functionality or logic.

### CODE REVIEW

**Comment by johnoel** [comment]
Can you look at the scanned code warnings for nuts.cpp and rwm.cpp?

https://github.com/admb-project/admb/security/code-scanning

**Comment by Cole-Monnahan-NOAA** [comment]
That link doesn't work for me (404). Do you mean the unused variable warnings when compiling those files?

**Comment by johnoel** [comment]
@Cole-Monnahan-NOAA, can you resend the pull request to branch/admb-12.3?

**Comment by johnoel** [comment]
Changes in f52aedd will be added pull request #182.

**Pull request closed without merging**
